### ISSUE TITLE
API proposal: url synchronisation

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#138]
Following discussions and requests from #40 #127, given all the different implementations out there to maintain/set/read the search state in the url, I feel it's time to really tackle this.

Does it belongs to the helper? Given the number of time we had to implement it in many demos, I guess yes.

Is this a problem to talk about browser specific need since our helper is ["Universal"](https://medium.com/@mjackson/universal-javascript-4761051b7ae9)? Seems no big deal since we can expose some feature only to the browser.

We propose to add a `algoliasearchHelper.ux` namespace and `algoliasearchHelper.ux.urlSync` to the `algoliasearchHelper` to store this feature and all the ux related feature we will add.

## Goal

When using the helper url synchronisation, we should be able to have a working refresh/back/forward browser button that will reset the page to where we were.

### Simple usage

```js
var helper = algoliasearchHelper(client, indexName);
var urlSync = algoliasearchHelper.ux.urlSync(helper, {
  // auto: true,
  // useHash: false
  // only: ['list', 'of', 'sensible', 'defaults', 'parameters']
});
```

### Advanced usage: use `location.hash`

```js
var helper = algoliasearchHelper(client, indexName);
var urlSync = algoliasearchHelper.ux.urlSync(helper, {
  useHash: true
});
```

### Advanced usage: `urlSync.setStateFromURL([URL])`

Useful when you want to manage everything by yourself. Or if you are
server-side.

Using the current url
```js
var helper = algoliasearchHelper(client, indexName);
var urlSync = algoliasearchHelper.ux.urlSync(helper, {
  auto: false
});
urlSync.setStateFromURL(); // reads the current URL
helper.search();
```

Manually giving a URL (can be used server side)
```js
var helper = algoliasearchHelper(client, indexName);
var urlSync = algoliasearchHelper.ux.urlSync(helper, {
  auto: false
});
urlSync.setStateFromURL('q=salut&hitsPerPage=200'); // takes a manual url (partial or full url)
helper.search();
```

### Advanced usage: `urlSync.getStateAsQueryString([opts])`

Useful when you want to manage everything by yourself.  Or if you are
server-side.

```js
var helper = algoliasearchHelper(client, indexName);
var urlSync = algoliasearchHelper.ux.urlSync(helper);
helper.search('salut');

//...

urlSync.getStateAsQueryString();
// q=salut&hitsPerPage=200
// there's no `?` appended, like what it is when you ask for `window.location.search`
```

## Requirements

- It should be possible to ask the helper to maintain the search state in the url (off by default)
- use `location.search` by default ("real" query strings), and have an option switch to `location.hash`
- use history API and provide the [necessary](http://caniuse.com/#feat=history) [fallback](https://github.com/devote/HTML5-History-API) for IE < 10
- use a deep object query string formatter like [hapijs/qs](https://github.com/hapijs/qs) and store it in the url bar in decoded mode (decodeURIComponent(querystringFromQs), it's fine)
- do not completely overwrite the current query string or hash, only overwrite known parameters and add everything else after
  - so that a client using things like anchors or expecting a certain query string to always be there will not be surprised
- we will have to have a angularjs-helper build that will handle the urlsync using [$location](https://docs.angularjs.org/api/ng/service/$location).search: 

## Implementation flow

@bobylito already did some good work here: https://github.com/algolia/algolia-ui-kit/blob/51de2fe5e9665e71c96e1a5e1474babf1ddca5d3/src/setup/url.js

what do you think?

**Comment by redox** [comment]
Not sure about the `urlSync` wording but cannot find better right now.

In Angular.js (and probably other frameworks), you don't deal with the raw query string but with an object: could we ensure `qs` is able to deal with that as well (https://docs.angularjs.org/api/ng/service/$location#search).

Otherwise, LGTM :+1:

**Comment by vvo** [comment]
> In Angular.js (and probably other frameworks), you don't deal with the raw query string

Can you precise your need here?

**Comment by vvo** [comment]
> Not sure about the urlSync wording but cannot find better right now.

- syncStateToURL
- syncStateWithURL
- URLSync

**Comment by redox** [comment]
>> In Angular.js (and probably other frameworks), you don't deal with the raw query string

>  Can you precise your need here?

I want to be able to use `$location.search()` to sync the state in the URL:
 * `helper.setStateFromURL($location.search())`
 * the Angular build should be able to use `$location.search('q', state.query).search('facetFilters[]', 'foo:bar')...` to change the URL

**Comment by vvo** [comment]
> helper.setStateFromURL($location.search())

So you want to manually set the state from URL but using an angularJS specific object notation (`$location.search()`)?

I guess in this case either you let the helper sync the url for you (auto sync), or you manually set the state with `helper.setState`?

As we do not have specific helper builds for angular, how would I know that the call to `helper.setStateFromURL()` was given an angular.js $location.search() object? Query string to object format is not something standard. That's why dealing with strings on the API level is the easiest.

> the Angular build should be able to use $location.search('q', state.query).search('facetFilters[]', 'foo:bar')... to change the URL

This is already doable right?

**Comment by vvo** [comment]
The usecase for `helper.setStateFromURL(url)` is more a server side feature (isomorphic app doing server side render) than a browser one I guess.

**Comment by bobylito** [comment]
The url handling should not be inside the helper : 
 - so we can change it easily, either us or a user
 - so it doesn't weight in the package of the helper
 - because we don't need it to be and therefore avoid making the helper bigger than it already is
 - so the focus of the helper is clear
 - because urlSync is not a searchParameter nor a managed search parameter, therefore it's not consistent with the current helper options

Also debouncing is not the correct strategy to apply here. It only makes the update weird.

Also I'm wondering : 
 - why don't the url mechanics go get the location itself  from the URL or the request (express/node n00b here)? 
 - can't we enhance the current events to provide a way for angular users to update their $location.search without having to hack/deal with a full fledge url management API?

@redox you can already do `helper.setState( $location.search() )` or `algoliasearchHelper( client, index, $location.search() )` since both are object based.

**Comment by vvo** [comment]
I do understand your point about the helper being a search helper and not a UI helper. Makes sense now that I think about it.

But where do we put this feature? Is it time for the algolia-ux-helper (programmatic interface) then?

We are in a weird state where the helper is the defacto library we advise to use when you want to build a search UX. But it seems not sufficient because you still need a lot of boilerplate to do: sync urls, sliders, autocomplete, instant, faceting, disjunctive on a UX side.

If we create another module then we must ensure that it will be self-sufficient and does not requires the user to load: algoliasearch-client-js, algoliasearch-helper-js, algoliasearch-helper-ux-js etc..

**Comment by vvo** [comment]
> why don't the url mechanics go get the location itself from the URL or the request (express/node n00b here)?

Did not get it

**Comment by vvo** [comment]
For reference (and it does not change that I do agree with you):

> so we can change it easily, either us or a user
be it in another module or inside the helper, there always the same problem. Also not a problem if you provide the underlying APIS (like setStateFromURL, getStateAsQueryString etc)
> so it doesn't weight in the package of the helper
The helper is currently 16kb gzipped I would not expect it to go more than 18kb gzipped by having the url thing.

**Comment by seafoox** [comment]
That's right that this feature is more related to the UI than the search functionally itself. But in the same time we want to help our users to build awesome implementation by providing them an handy toolbox.

Debouncing
-
Regarding the refresh of the URL, I agree with @bobylito that debouncing is probably not the way we should do it. 

> Also debouncing is not the correct strategy to apply here. It only makes the update weird.

I'd be personally prefer to update it, when the end-user focus out form the search field. We could imagine to have the search field selector as a config param, and if that one is missing, fallback to the debounced version

```javascript
var helper = algoliasearchHelper(client, indexName, {
  urlSync: {
    useHash: true,
    searchInputSelector: '#my-search-input'
  }
});
```

Naming
-
For the naming what do you think about `refreshUrl: true`?

Mapping
-
Otherwise, I was wondering if you think it could make sense to allow people to pass URL mappings, so they could generate clean URLs: for both sharing and SEO. For instance in the case we have a record that looks like that 
```json
{
	"category": "Data Cables",
	"manufacturer": "Apple®",
	"name": "Apple® - 3.3' Lightning-to-USB 2.0 Cable",
	"salePrice": 19.99,
	"salePrice_range": "1 - 50",
	"shortDescription": "Compatible with most Apple&#174; iPad&#174;, iPhone&#174; and iPod&#174; models with a Lightning connector; charges and syncs your device; reversible design",
	"thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/6652/6652043_s.gif",
	"type": "HardGood",
	"url": "http://www.bestbuy.com/site/apple-3-3-lightning-to-usb-2-0-cable/6652043.p?id=1218803451837&skuId=6652043&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ"
}
```
With the attributes `category`, `manufacturer` and `type` declared as facets. We could then have something like:
```javascript
var helper = algoliasearchHelper(client, indexName, {
  urlSync: {
    useHash: false,
    pattern: '/catalog/{{ type }}/{{ category }}/{{ manufacturer }}
  }
});
```
_We would still find a way to display disjunctiveFacets_

What do you think?

**Comment by vvo** [comment]
handed in #203
