### ISSUE TITLE
Distinct forced to False

### ISSUE THREAD

**Issue by Jastrzebowski** [algolia/algoliasearch-helper-js#150]
Hi I'm having a strange bug while making a simple request (first page of an listing) using Search Helper, even though I force `distinct` to be `true` it's overwritten to `false`.

Code:
```javascript
helper = algoliasearchHelper(client, INDEX, {
  facets: [ "recruiting" ],
  disjunctiveFacets: [ "branches", "city", "country", "employeesRange" ]
})
helper.setQueryParameter("distinct", true).search()
```

It seams to be connected with this line: https://github.com/algolia/algoliasearch-helper-js/blob/master/src/algoliasearch.helper.js#L559 (from the commit c8560a25a82313777e1c08d7a009eb0be913554f)

**Comment by bobylito** [comment]
Thanks @Jastrzebowski for the issue.

It is the expected behaviour, otherwise the algolia would return an error. The restriction only exist when there is no filter at all. Once you add a refinement or use a query, the value of distinct is the one from your configuration. We made some test for that : https://github.com/algolia/algoliasearch-helper-js/blob/master/test/spec/helper.distinct.js

**Comment by redox** [comment]
Actually the behavior has changed 1 week ago @bobylito, it's now possible to do a distinct query with an empty query string and no filters -> do you mind removing it & release the next version?

**Comment by bobylito** [comment]
Yeah will do!

**Comment by Jastrzebowski** [comment]
Thx @bobylito and @redox!
