### ISSUE TITLE
Page parameter gets ignored whenever refinement is added 

### ISSUE THREAD

**Issue by nikhil-bhandari** [algolia/algoliasearch-helper-js#165]
I have a method that wraps up algoliasearch-helper, following is a snippet:
```
        self.query = function (options) {

            var config = {
                    hitsPerPage: options.hitsPerPage || 20,
                    page: options.page || 0
                },
            helper = algoliasearchHelper(algoliaClient, index, config);

            helper.addRefine("category", options.categoryId);
            helper.search();
        };
        self.query({page: 0});
        self.query({page: 1});
        self.query({page: 2});
```

When I inspect config and helper objects, `config.page` is correct but `helper.state.page` is always 0. 

This happens if I add any of the following:

helper.setQuery
helper.addRefine
helper.addNumericRefinement

I have seen the built in method to get page, but is it really necessary to keep the helper object in scope to get the next page?

**Comment by vvo** [comment]
Hi, @nikhil-bhandari, thanks for the bug report, confirming I am the same guy on support and github with this comment :)

**Comment by vvo** [comment]
I am confirming that the page is automatically reset to 0 when you do a refinement.

We originally implemented this behavior because this is what most people expect: When I am on page 3 of the current search. Adding another filter, I would expect to have back all the results, not just the page 3 of the new refinement combination.

To solve this behavior, you can:

```js
self.query = function (options) {

    var config = {
            hitsPerPage: options.hitsPerPage || 20
        },
    helper = algoliasearchHelper(algoliaClient, index, config);

    helper.addRefine("category", options.categoryId);
    helper.setPage(options.page);
    helper.search();
};

self.query({page: 0});
self.query({page: 1});
self.query({page: 2});
```

We are thinking about maybe not doing this anymore (resetting to 0) in another major release (future), because it does magic and thus results sometimes in support while it should have not.

What do you think @bobylito?

**Comment by vvo** [comment]
Also, @nikhil-bhandari, the helper is not meant to be instanciated at every query. Your best option would be to keep a reference to the helper somewhere in your application.

The helper is a stateful object that is best used by having one instance that you modify with our methods on and on.

**Comment by nikhil-bhandari** [comment]
@vvo  the setter for page is `helper.setCurrentPage()`. Can you edit your comment so that people don't get confused?

I was a bit confused about creating "multiple helpers vs a single helper". Actually I am querying multiple indexes in an angular controller and things were getting messy. So I thought about wrapping up the whole code inside a service and reusing it in all the controllers.

thanks for pointing it out. I'll try and refactor code for that. But can you explain any disadvantages that  because of this? I am just trying to figure out how critical is this.

Also let's say I have 2 indexes A and B and then A and B have some slave indexes that are used for sorting. 

Should I use the same helper to query all the indexes or should I change it when I switch to a different master.

**Comment by vvo** [comment]
> I was a bit confused about creating "multiple helpers vs a single helper". Actually I am querying multiple indexes in an angular controller and things were getting messy. So I thought about wrapping up the whole code inside a service and reusing it in all the controllers.

Maybe you can have an object like:

```js
var helpers = {
  indexNameOne: helperInstance,
  indexNameTwo: helperInstance2
};
```

Then use `helpers.indexNameOne.method()..`. The difference is that you are not executing the whole helper constructor and code at every query, only the relevant code, and you do not have to maintain any state on your side (for example, what are the current selected categories). You only have to input all of these parameters in the helper once and then add or remove or toggleRefine on your facets when the user clicks on your UI.

Otherwise, you would have to do a lot of work on your side at some point.

> Also let's say I have 2 indexes A and B and then A and B have some slave indexes that are used for sorting.
> 
> Should I use the same helper to query all the indexes or should I change it when I switch to a different master.

For sorting, you can use [helper.setIndex]( http://algolia.github.io/algoliasearch-helper-js/docs/AlgoliaSearchHelper.html#setIndex).

See our cheatsheet on [this subject](https://github.com/algolia/algoliasearch-helper-js/tree/20798ab1659ff69f48bef37b3da3dced3a34f641#index).

Let me know, otherwise close the issue when you are good to go!
