### ISSUE TITLE
where is disjunctiveFacets param?

### ISSUE THREAD

**Issue by argb** [algolia/algoliasearch-helper-js#191]
Why  can't I find "disjunctiveFacets" param in restful api document?
This helper make the js library more complex,disjunctive,conjunctive,AND,OR....what are these??
The original js lib there are no so many weird concepts.
what I want just want to get the search result and then display them as html,why make the clear rest api so complex?

**Comment by bobylito** [comment]
Hi @argb, thanks for asking this question :)

The helper is high level library built on top of our API to ease the integration of Algolia. The reason why have a disjunctiveFacets and hierarchicalFacets parameters in SearchParameters is those are not just simple disjunctive facets (filters assemble with or operators). The mechanism behind actually makes more request in other to get the hits for the actual filters and the facets values that can also be selected : 
 - one request with all the filters applies to retrieve the hits
 - one request per each filtered disjunctive or hierarchical facet filtered in order to retrieve other values that can be selected for further facetting

Also the Helper provides a way to manage the search state. This contains all the values the user might have set during his/her search.

If you are more at ease with this API, a JS API that is [closer to the REST API is also available](https://github.com/algolia/algoliasearch-client-js).

**Comment by argb** [comment]
thank you,maybe cause I am not native English speaker,and be a newbie for algolia,so many places can't understand good enough. I am trying to deeply learn algolia and try to apply to my project. I want to say algolia is a good product and solution,so hope it do better and better. Last words,a bit too expensive! :)
