### ISSUE TITLE
Expose browse, browseFrom and browseAll 

### ISSUE THREAD

**Issue by harrisbp** [algolia/algoliasearch-helper-js#225]
The search() method is limited by default in the algolia client to 1000 results, which makes no sense to begin with given the whole reason for using algolia is to power a search engine with hundreds of thousands of results...

Nonetheless, I think the browse* methods should be exposed in the helper for those of us with larger dataset requirements.

**Comment by bobylito** [comment]
Hi, thanks for creating this issue. :)

**Comment by harrisbp** [comment]
Absolutely! Currently we are using Algolia and the JS client and JS helper on https://snobswap.com/shop for our catalog. We have well over 90k items for sale and from the /shop page our SEO is very limited because at 40/page our site is limited to 25 pages.

Sure the average consumer isnt going to click through that many pages; however, SEO crawlers will go forever. 

Let me know if you need anything else. Seems like a pretty straightforward exposure given they take the same parameters...

**Comment by harrisbp** [comment]
What is the status of this request? I would like to know if I should rework my application or wait for the feature.

**Comment by vvo** [comment]
@harrisbp Thanks for taking the time to get back here.

The browse method requires an ADMIN key so you would not want to use it on the frontend.

Still, you can use the browse method of the js client on the backend for your SEO needs. There should be no need for the helper to implement this method, but maybe I am missing something here.

On the SEO side, I would not advise you to do so. Indeed search engine crawlers may seem to want to crawl and crawl and crawl but that's only because the more they ask, the more you give them links. We do not recommend our users to index so much results in search engines.

Indeed search engines are more and more concerned about having meaningful results: they want results that the humans will be looking for.

For instance, no human should be looking for page 20 in your website but the robots. That's why we do not recommend trying to put thousands of search results in search engines. What the search engines are interested in are main categories search pages, products pages. But having (outdated) page 200 of a particular search on google will not help your client find you and thus search engines should not rank you more on the long term.

I would advise you to either:
- use the browse method from the js client, server side
- do not try to index so much pages in search engines and stop your pagination at 20 for example.

Let me know what you think.

**Comment by harrisbp** [comment]
@vvo Thanks for the response...

While I agree with your assessment of the human element of results, I completely disagree with your solutions.

We are using Algolia as our main interface for browsing the catalog. When we offer the user a 200 per page item count, it makes us looks rather small and insignificant when only 5 pages of results are available. Exposing my admin key in the JS is a terrible solution and forcing me to do it from the server side prevents us from using any of the CDN, near real time results Algolia is able to provide.

Handcuffing developers from gaining access to search results is not a great way of doing business. Certainly offering a use-case and suggested parameters to search is one thing, but to say do this or else expose your key, that's not right.

I look forward to discussing this further...

Brian

**Comment by vvo** [comment]
Hi again, I am sorry to hear your use case is not doable given our 1000 hits search result limit.

Indeed doing it on the backend would prevent you from using algolia in the best conditions.

There is no good answer here because the main usecase Algolia was built in mind was not search results of 200 hits but rather amazon style search results of 20 relevant hits.

Can you link me to a demo of your website? Maybe via support@algolia.com if thats relevant.

So that we better understand your use case.

**Comment by vvo** [comment]
Also please understand that the 1000 hits limit is here to keep those 1000 hits very fast to compute. Its a performance requirement that is powering the Algolia speed.

**Comment by harrisbp** [comment]
Just emailed you at the support email address.

Brian

On Monday, October 26, 2015, Vincent Voyer <notifications@github.com> wrote:

> Hi again, I am sorry to hear your use case is not doable given our 1000
> hits search result limit.
>
> Indeed doing it on the backend would prevent you from using algolia in the
> best conditions.
>
> There is no good answer here because the main usecase Algolia was built in
> mind was not search results of 200 hits but rather amazon style search
> results of 20 relevant hits.
>
> Can you link me to a demo of your website? Maybe via support@algolia.com
> <javascript:_e(%7B%7D,'cvml','support@algolia.com');> if thats relevant.
>
> So that we better understand your use case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/algolia/algoliasearch-helper-js/issues/225#issuecomment-151309097>
> .
>


-- 
*Brian P. Harris*
President

Ameronix
7400 Beaufont Springs Dr. Ste 110
Richmond, VA 23225
(804) 272-1200 Ext: 101
(804) 272-1201 - Direct

-- 
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by vvo** [comment]
Ok will get back to you on tomorrow morning CET

**Comment by vvo** [comment]
Reopening, I wonder how we could:
- keep the refinements possibilities
- while using the browse method based on an option, to get pass the 1000 hits limit

Any ideas @bobylito?

**Comment by ippy04** [comment]
:+1:

**Comment by bobylito** [comment]
@harrisbp @ippy04 I have some ideas but I need to understand how you use the browse API yourself. Do you usually all the results until the very end, or do you usually stop at some point? Do you use it as a search without limits? Any information on how you use it will help us making a meaningful API :)

**Comment by xiaolin** [comment]
Any updates on this? I'm experiencing the same issue.

**Comment by redox** [comment]
> Reopening, I wonder how we could:
> 
> keep the refinements possibilities
> while using the browse method based on an option, to get pass the 1000 hits limit
> Any ideas @bobylito?

You cannot use the `browse` function for the first hits because the results won't be ordered by relevance (that's the drawback allowing the browse to go over that 1000 hits limit).

The only thing you could do is use the `search` until hit 1000th; and then switch to `browse` -> but we don't have any smart way to remove the 1000th you've seen from the `browse` results set.

**Comment by jbardnz** [comment]
Hey Guys, 

We are in the exact same situation as @harrisbp we have a ecommerce store and the browse/search page is powered by Algolia. If a user comes to this page and has no filtering on we have 10,000+ results to show but we are unable to show over 1000.

It seems a bit crazy to not be able to access the browse() function in this API.

Just an opinion on how you have architectured this. It would be much more helpful to me if I could get unlimited results from search() with the caveat that after 1000 results speed and/or relevancy won't be as good. (In the background the helper could fallback to the browse() API)

As it is now I simply can't show all the results we have to users which is much worse than the query just being a little slow.

**Comment by bobylito** [comment]
After much thoughts we've decided not to move forward with this issue. The primary usage of the helper is user facing search. The `browse` feature is provided on the Algolia API for backup and export purpose. Therefore I am closing this issue.
