### ISSUE TITLE
Is removeStopWords supported?

### ISSUE THREAD

**Issue by xiaolin** [algolia/algoliasearch-helper-js#304]
I'm getting a warning, 

Unknown SearchParameter: `removeStopWords` (this might raise an error in the Algolia API)

Was wondering if this is supported by the `algoliasearch-helper`

Thanks,

**Comment by bobylito** [comment]
Hi @xiaolin 

This warning is meant to tell you that this parameter is not explicitly supported in the helper but it will be sent to Algolia API. Just don't be surprise if you get an error from the API. Also be careful to listen to the `error` event otherwise you won't be able to understand if you don't get a result.

Does this answer your question?

**Comment by xiaolin** [comment]
Makes sense. Is there a plan to add it as a supported parameter?

**Comment by bobylito** [comment]
We are moving forward with #360 so this won't be an issue anymore. Thanks @xiaolin again for pointing out the problem with the current behaviour.
