### ISSUE TITLE
disjunctive vs numeric refinements operations count

### ISSUE THREAD

**Issue by reinaris** [algolia/algoliasearch-helper-js#307]
Using latest versions from cdn:
```
<script src="//cdn.jsdelivr.net/algoliasearch/3.13.1/algoliasearch.min.js"></script>
<script src="//cdn.jsdelivr.net/algoliasearch.helper/2.9.1/algoliasearch.helper.min.js"></script>
```

Doing:
```
helper.addNumericRefinement('name_id', '=', 1);
helper.search();
```
will count as 1 operation.

While:
```
helper.addDisjunctiveFacetRefinement('name', 'bobylito');
helper.search();
```
will count as 2 operations.

I was wondering why numericRefinement are 'free of charge' while addDisjunctiveFacetRefinement or toggleRefinement will count as operations. The more active disjunctive refinements I have the more operations it will count.

Could be a reason for me to try to use as less disjunctive refinements as possible :)

**Comment by vvo** [comment]
Hi @reinaris indeed disjunctiveRefinements are currently counting twice and this is not a bug. Ideally we would like not to have to do two requests to get them, because it takes more time for the user AND it counts twice in your account.

Disjunctive refinements are a way to do "OR" selections (first request) while keeping the "count" for each facet value relative to all the current filters (second request).

Disjunctive refinements are not a standard Algolia API engine feature, they are built into the helper for now and this is why we need to make multiple requests.

While numeric refinements is a standard Algolia API engine feature and thus we do not need to to do multiple requests to get all the data we need.

> The more active disjunctive refinements I have the more operations it will count.

Yes that is true.

> Could be a reason for me to try to use as less disjunctive refinements as possible :)

I can understand that, so use disjunctive refinements only when necessary given your usecase.
