### ISSUE TITLE
Helper generated URL with numeric refinement isn't Facebook friendly

### ISSUE THREAD

**Issue by mmhan** [algolia/algoliasearch-helper-js#459]
Sharing the following search url with numeric refinement to facebook would result in Facebook sanitizing the URL to strip them of html tag resulting in a malformed URL.

Orignal : `http://www.example.com/search?nR[price][<=][0]=1000&nR[price][>=][0]=400`

After Sanitizing : `http://www.example.com/search?nR[price]=][0]%3D400`

Wondering if there's any workaround for that.

**Comment by bobylito** [comment]
Hi @mmhan thanks for the issue. If you're building your app with the Helper directly, what you can do is build your own / not generic URL creator.

You could probably use [helper.getState](https://community.algolia.com/algoliasearch-helper-js/reference.html#AlgoliaSearchHelper#getState) instead of [getQueryStringFromState](https://community.algolia.com/algoliasearch-helper-js/reference.html#algoliasearchHelper.module:url.getQueryStringFromState), which will let you filter the state to only the elements that you wish. For example, if I wanted to get only the query and the numeric filter price:

```js
helper.getState(['attribute:price', 'query']);
```

Then you should transform it to your liking for the URL form, and afterwards you could use [`qs`](https://www.npmjs.com/package/qs) for serializing.

**Comment by bobylito** [comment]
@mmhan Have you had any issue implementing what I suggested?

**Comment by mmhan** [comment]
I haven't actually get around to it yet.

**Comment by bobylito** [comment]
Is there something that is missing to make my explanation clearer? @mmhan
