### ISSUE TITLE
Search in multiple indices 

### ISSUE THREAD

**Issue by basschoen** [algolia/algoliasearch-helper-js#468]
Is it possible to search in multiple indices, but retrieve the results in a single response. We have multiple indices: Zendesk and WordPress, but we want a single search result with both Zendesk and WordPress results. We want this because if the Zendesk post is more relevant than the WordPress one, we want that post to show above the other post.

Is it possible to either merge indices (automatically) or to search in multiple indices (and retrieve the results in a single response, so without the 'derive' function)?

**Comment by bobylito** [comment]
Hi @basschoen yes it is possible to search in multiple indices with a single HTTP request using the [derive feature of the JS Helper](https://community.algolia.com/algoliasearch-helper-js/concepts.html#derivations-of-the-helper-multi-queries). However multiple result-sets can't be merge. This is because each index will have different different ranking formulas.

**Comment by basschoen** [comment]
@bobylito thanks for the quick response! But it's also not possible to automatically merge multiple indices via the dashboard and search that index?

**Comment by bobylito** [comment]
No it's not. It could be possible to upload the data inside a single index but I guess that would require to customise the integrations.

**Comment by basschoen** [comment]
@bobylito Ok, that's clear, thanks! Any plans on adding this feature?

Is it otherwise possible to retrieve a 'score' or some value the results are being sorted on by Agolia? That way I'm possible to merge the two results myself.

**Comment by basschoen** [comment]
Could use the getRankingInfo for that I guess?

**Comment by bobylito** [comment]
There is a score value, but since the ranking formula is different as is the dataset the comparaison of scores of results from different different indices won't be meaningful. Sorry.

I don't think we plan on adding a merge feature. However I will transmit your request to raise the awareness on the subject either in the API or on the integration level.

**Comment by gosupernova** [comment]
+1 This would be great across our Jekyll site and Wordpress blog 👍
