### ISSUE TITLE
How to Uses helper.reset() in a widget ?

### ISSUE THREAD

**Issue by Asahro** [algolia/algoliasearch-helper-js#600]
I am trying to creat a widget when it active all filter before be un active. can I use helper.reset ?
and how to use it ?

```js
search.addWidget(
  instantsearch.widgets.refinementList({
    container: '#tag',
    attributeName: 'tag',
    limit: 5,
    operator: 'and',
    transformData:{
      item:function(data){
        data.label = toUpper(data.label);
        return data;
      }
    },
    templates: {
      item: facetTemplateCheckbox3,
      header: ''
    }
  })
);
```

**Comment by Haroenv** [comment]
```js
search.addWidget(
  instantsearch.widgets.clearAll({
    container: "#clear",
  })
);
```

See the full documentation [here](https://community.algolia.com/instantsearch.js/v2/widgets/clearAll.html).

I'm going to close this issue since it's more related to InstantSearch than the helper. Feel free to open a  new issue in [algolia/instantsearch.js](https://github.com/algolia/instantsearch.js) if necessary.

**Comment by Haroenv** [comment]
Sorry @Asahro, I don't understand what you mean. Can you give a bit more info please?

**Comment by bobylito** [comment]
Can you give us access to your code?

**Comment by Asahro** [comment]
thank for your answared, my code is like this demo.
https://community.algolia.com/instantsearch.js/v1/examples/media/
I wanna try if the i chose the ratting filter, another active filter be unactive
