### ISSUE TITLE
Why is this module so big?

### ISSUE THREAD

**Issue by joker-777** [algolia/algoliasearch-helper-js#617]
I juse `react-instantsearch` which includes this module. In the webpack analyzer I can see that `algoliasearch-helper` needs quite some space. Why?

![algoliasearch_helper_graph](https://user-images.githubusercontent.com/378859/43799731-a0154c18-9a8e-11e8-83a7-4672e9ac5e59.jpeg)

**Comment by Haroenv** [comment]
Hey @joker-777, this is something we are aware of, a big reason this is a big module is because it's using lodash. It's not quite straightforward to simply undo that usage because most methods we are using accept both arrays and objects, so it's a not insignificant amount of work. Secondly part of this is because of older parts of the API that are now handled by React InstantSearch (e.g. URL Sync) are in here, and can't be simply removed without a major version. 

Unfortunately I don't have much more answer for you now, but we will work on this to make the module smaller in the future. If you're seeing obvious things that can shrink the code without too much work we can do those suggestions or merge those PRs before doing a significant effort too.

**Comment by Haroenv** [comment]
Some sizes I have computed to see what is the biggest wins (everything I can think of is breaking change though, but stuff not used in our libraries)

```
Helper 35.3 kB
Helper - url 31.3 kB
Helper - url - SearchParameters 25 kB
Helper - url - SearchResults 24.8 kB
Helper - url - SearchParameters - SearchResults 17 kB
Helper - url - SearchParameters - SearchResults - events / util 12.7 kB
Helper - url - SearchParameters - SearchResults - AlgoliaSearchHelper 488 B
```

**Comment by staabm** [comment]
Just want to also confirm, that InstantSearch javascript is way to big:

https://twitter.com/markusstaab/status/1094135682656808961

**Comment by Haroenv** [comment]
Thanks for crossposting here @staabm, the main reason is indeed here too. One way to already get a smaller size, is by using code splitting (using a build tool, and importing only the used parts of InstantSearch). Updating to InstantSearch v3 (you're on v1) also will save about 30% already.

**Comment by staabm** [comment]
> Updating to InstantSearch v3 (you're on v1) also will save about 30% already.

oh thats interessting. do I need to handle any BC breaks between v1 and v3, or can I just transparently update it?

**Comment by Haroenv** [comment]
There's a migration guide from v1 to v2 and from v2 to v3 here: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/js/

There's definitely some breaking changes, but mostly naming changes

**Comment by Haroenv** [comment]
Recent quick experiment I did for changing the event emitter. util + events → mitt. It's not entirely straightforward; see https://github.com/developit/mitt/issues/90

**Comment by Haroenv** [comment]
This is fixed in v3 (yay finally!) You can already use the canary versions. I'll close this issue since our work on it is done, we went from:

97kb / 30kb gz

to 

42kb / 10kb gz

https://bundlephobia.com/result?p=algoliasearch-helper@0.0.0-27095c0

Over time we hope to still decrease it by removing unneeded methods, but no major changes will happen further (ie we won't rewrite it fully)
