### ISSUE TITLE
Log can not be thrown

### ISSUE THREAD

**Issue by tomoktan** [algolia/algoliasearch-helper-js#634]
Hi,

I use this module for search.
However, this search query did not throw a log on the Dashboard.

This module has need parameters to throw the logs?
I could not find it.

```js
# I was not able to check the log on the dashboard.

const algoliasearch = require('algoliasearch');
const client = algoliasearch('ALGOLIA_APPLICATION', 'ALGOLIA_API_KEY');
const indexName = 'MY_INDEX_NAME'
const algoliaSearchHelper = require('algliasearch-helper');

const search = async (params, sort, disjunctiveFilters, category) => {
  const helper = algoliaSearchHelper(client, indexName, params);

  if (disjunctiveFilters.area && disjunctiveFilters.area.length) {
    disjunctiveFilters.area.forEach(city => {
      helper.addDisjunctiveFacetRefinement('addressLevel.lv3', city);
    });
  }

  if (disjunctiveFilters.rate) {
    helper.addNumericRefinement('rate.score.f5', '>=', disjunctiveFilters.rate);
  }

  helper.addFacetRefinement('category', category);
  helper.setPage(params.page);
  const response = await helper.searchOnce();
  const { hits, nbHits, disjunctiveFacets } = response.content;
  const facets = normalizeFacets(disjunctiveFacets);

  return { hits, nbHits, facets };
};
```

```
# I was able to check the log on the dashboard.

const algoliasearch = require('algoliasearch');
const client = algoliasearch('ALGOLIA_APPLICATION', 'ALGOLIA_API_KEY');
const index = client.initIndex('MY_INDEX_NAME');

const search = async params => {
  const { hits, nbHits } = await index.search(params);
  return { hits, nbHits };
};
```

**Comment by samouss** [comment]
Hi, the issue is not inside your code but on the dashboard. The difference between the two samples of code is how the JavaScript client make the request. The first example trigger a request to Algolia on the [multi queries endpoint](https://www.algolia.com/doc/rest-api/search/#search-multiple-indices), the other on the [single query endpoint](https://www.algolia.com/doc/rest-api/search/#search-index-post). The calls to the multi queries endpoint are not displayed inside the logs tab of the dashboard. You can still access them via the [`getLogs`](https://www.algolia.com/doc/api-reference/api-methods/get-logs/) method on the client.

**Comment by tomoktan** [comment]
Thank you @samouss 
I understand.
