### ISSUE TITLE
None of the examples in the README show error handling

### ISSUE THREAD

**Issue by rauchg** [algolia/algoliasearch-helper-js#636]
I found it quite strange that no mention of the `error` is event is made in the README's examples.

The semantics are not described, however. Is it a one-time event? Or can we expect it to fire multiple times? Can it happen after `result` is emitted?

An example is:

```
var algoliasearch = require('algoliasearch');
var algoliasearchHelper = require('algoliasearch-helper');

var client = algoliasearch('appId', 'apiKey');

var helper = algoliasearchHelper(client, 'indexName', {
  facets: ['mainCharacterFirstName', 'year'],
  disjunctiveFacets: ['director']
});

helper.on('result', function(data){
  console.log(data.hits);
});

helper.addDisjunctiveFacetRefinement('director', 'Clint Eastwood');
helper.addDisjunctiveFacetRefinement('director', 'Sofia Coppola');

helper.addNumericRefinement('year', '=', 2003);

// Search for any movie filmed in 2003 and directed by either C. Eastwood or S. Coppola
helper.search();
```

Maybe it'd be helpful to add the `'error'` event handling there.

**Comment by rauchg** [comment]
Update: searched a bit more and found `searchOnce`, which I believe helps me.

**Comment by rauchg** [comment]
It seems however the lack of error handling is a bit widespread. An example is that the `'error'` event is also absent in the React Native example:

https://github.com/algolia/hn-reactnative-sample/blob/master/components/SearchPage.js#L26-L28

**Comment by Haroenv** [comment]
Thanks for mentioning this @rauchg, indeed we might have neglected the error state since overall it hasn't been necessary in many of the more regular use cases. However in React InstantSearch, we expose any internal errors with the [`connectStateResults`](https://community.algolia.com/react-instantsearch/connectors/connectStateResults.html) HoC. 

I was wondering why you are more inclined to use the lower-level "helper" library, and not React InstantSearch. Does that have a particular reason, or do you have some feedback? 

Thanks! 


To answer your initial question, the `error` event would happen every time a `result` was expected; but instead it errored, and didn't give that result. So you can never have a result with an error event, or never have an error event and also a result event. Both events can only be triggered from the `search` method on the helper
