### ISSUE TITLE
Ability to get all refined values

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-helper-js#70]
Something like `helper.getRefinements(facet) -> ["value1", "value2", ...]`

**Comment by bobylito** [comment]
@redox should it work for any kind of refinement? Or should we have different methods for each type of refinement?

**Comment by redox** [comment]
Hmmm, I would say any kind:

```js
addRefine('c1', 'v1');
addDisjunctiveRefine('d1', 'v1');
addDisjunctiveRefine('d1', 'v2');
addRefine('c2', 'v1');
addExclude('c2', 'v2');

getRefinements('c1') -> ['v1']
getRefinements('d1') -> ['v1', 'v2']
getRefinements('c2') -> ['v1', '-v2'] // with a "-" ? -> not sure about that one
```

**Comment by bobylito** [comment]
Humm different types of refinements. I see three options here : 
 
- one function, return the values for all refinements, without distinction. The context should be obvious, but that may not be the case for exclusions
- one function, return the values for all refinements, with a more structured data (map containing the type of refinement as the key) or labels (tuple of type, value?). it's less obvious to read.
 - one function per type, returns a list of values for the type. We need to provide less information, the user should know which function to call because he knows the context. Makes more API...

**Comment by redox** [comment]
The use case was to efficiently/quickly build a list of all active refinements on top of the page, with the ability to remove filters clicking on them. The last option should work, not yet sure it's the most efficient way to do it because of the switch/case on the type of the facet that could make things more complex.

Ideally I would like to write something like on top on my hits:
```
FOREACH facet IN facets:
  FOREACH refinement in helper.getRefinements(facet):
     <span class="label">refinement <a href="#" ngclick="helper.removeRefinement(facet, refinement)">x</a></span>
```

**Comment by redox** [comment]
The `getRefinements` would then only be at the `AlgoliaSearchHelper` level, and the "one function per type" at the `SearchParameter` level.

**Comment by bobylito** [comment]
I'm ok with you latter comment but don't you think that each kind of facetting has its own UI?

**Comment by redox** [comment]
They have their own UI in the facets, but if you want to add something on top of the results page they could share the same. But also, it's so easier to use because you just don't need to think about their types.

**Comment by bobylito** [comment]
:+1: Go then! :)
