### ISSUE TITLE
TypeError: Cannot read property 'facets' of undefined

### ISSUE THREAD

**Issue by raapperez** [algolia/algoliasearch-helper-js#710]
Sometimes our users get the error `TypeError: Cannot read property 'facets' of undefined`

From: `webpack:///./node_modules/algoliasearch-helper/src/SearchResults/index.js line 412`

There are 60 occurrences (37 users) of this type.
We couldn't find a way to reproduce.

**Comment by Haroenv** [comment]
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js). Thanks!

This error is likely happening because of some incorrect setup of facets. 

Which version of the helper are you using?

<details>
<summary> team notes </summary>

This error can no longer happen in v3, since we are passing a default value

https://github.com/algolia/algoliasearch-helper-js/blob/2472e4c1b5f76b990a032104a08e90e76996032f/src/SearchResults/index.js#L431

</details>
